import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.repxpert.com.tr/tr');
  await page.getByText('Ürün numarası, OE numarası,').click();
  await page.getByRole('textbox', { name: 'Ürün numarası, OE numarası,' }).fill('p61032');
  await page.getByRole('textbox', { name: 'Ürün numarası, OE numarası,' }).press('Enter');
  await page.getByRole('link', { name: 'Fren balata seti, diskli fren PRIME LINE BREMBO  P 61 032 / Fren balata seti,' }).click();
  await page.getByRole('treeitem', { name: 'RENAULT' }).click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('CLIO I Kasa/eğik arka (S57_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('CLIO I Kasa/eğik arka (S57_)').click();
  await page.getByText('CLIO II (BB_, CB_) | CLIO MIO').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('CLIO II (BB_, CB_) | CLIO MIO').click();
  await page.getByText('MEGANE I (BA0/1_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('MEGANE I (BA0/1_)').click();
  await page.getByText('MEGANE I Cabriolet (EA0/1_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('MEGANE I Cabriolet (EA0/1_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('CLIO I Kasa/eğik arka (S57_)').click();
  await page.getByText('CLIO I Kasa/eğik arka (S57_)').click();
  await page.getByText('CLIO II (BB_, CB_) | CLIO MIO').click();
  await page.getByText('CLIO II (BB_, CB_) | CLIO MIO').click();
  await page.getByText('MEGANE I (BA0/1_)').click();
  await page.getByText('MEGANE I (BA0/1_)').click();
  await page.getByText('MEGANE I Cabriolet (EA0/1_)').click();
  await page.getByText('MEGANE I Cabriolet (EA0/1_)').click();
  await page.getByText('MEGANE I Classic (LA0/1_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('MEGANE I Classic (LA0/1_)').click();
  await page.getByText('MEGANE I Coach (DA0/1_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('MEGANE I Coach (DA0/1_)').click();
  await page.getByText('MEGANE I Grandtour (KA0/1_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('MEGANE I Grandtour (KA0/1_)').click();
  await page.getByText('MEGANE I Hatchback Van (SA0/').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('MEGANE I Hatchback Van (SA0/').click();
  await page.getByText('SUPER 5 (B/C40_)').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('SUPER 5 (B/C40_)').click();
  await page.getByText('THALIA I (LB_) | SYMBOL |').click();
  await page.getByText('CLIO I (B/C57_, 5/357_) |').click();
  await page.getByText('THALIA I (LB_) | SYMBOL |').click();
});